// do not edit this file - it was generated - edit ./bundle.ts.tpl

///<reference path='../backbone.d.ts' />
///<reference path='../underscore.d.ts' />

/// <reference path='bundleLoader.ts' />
/// <reference path='components.ts' />
/// <reference path='behaviours.ts' />
/// <reference path='validators.ts' />
/// <reference path='controls.ts' />







"ts file must not be empty to prevent invalid source maps - see https://typescript.codeplex.com/workitem/2132";
